### ISSUE TITLE
Implement basic query for frontend implementation

### ISSUE THREAD

**Issue by nicolas-bastien** [smartbooster/content-bundle#5]
## Goal

Provide default behavior for frontenf implementation

## Todo

- [ ] repositories get last order by date with a limit
- [ ] post get last publication date
- [ ] Post get previous and next for navigation
- [ ] get category/tag with published post

## Missing

Implement db testing to validate each query.

**Comment by nicolas-bastien** [comment]
@r-ichard do see something missing in this issue ?
